### ISSUE TITLE
Unable to add NestEmitterModule in app.module on NestJS v6.0.0

### ISSUE THREAD

**Issue by Thomas-Ahn** [nestjs-community/nest-emitter#6]
It could be the same issue with NestJS v6.0.0 update, but here is error message I got when start nestjs app.

[Nest] 77452   - 04/04/2019, 3:33 PM   [NestFactory] Starting Nest application...
[Nest] 77452   - 04/04/2019, 3:33 PM   [ExceptionHandler] Nest cannot export a provider/module that is not a part of the currently processed module (NestEmitterModule). Please verify whether each exported unit is available in this particular context. +17ms
Error: Nest cannot export a provider/module that is not a part of the currently processed module (NestEmitterModule). Please verify whether each exported unit is available in this particular context.
    at Module.validateExportedProvider (/opt/vrs/eslnest/node_modules/@nestjs/core/injector/module.js:224:19)
    at Module.addCustomExportedProvider (/opt/vrs/eslnest/node_modules/@nestjs/core/injector/module.js:208:43)
    at Module.addExportedProvider (/opt/vrs/eslnest/node_modules/@nestjs/core/injector/module.js:194:25)
    at NestContainer.addExportedProvider (/opt/vrs/eslnest/node_modules/@nestjs/core/injector/container.js:112:16)
    at DependenciesScanner.insertExportedProvider (/opt/vrs/eslnest/node_modules/@nestjs/core/scanner.js:170:24)
    at exports.forEach.exportedProvider (/opt/vrs/eslnest/node_modules/@nestjs/core/scanner.js:101:50)
    at Array.forEach (<anonymous>)
    at DependenciesScanner.reflectExports (/opt/vrs/eslnest/node_modules/@nestjs/core/scanner.js:101:17)
    at DependenciesScanner.scanModulesForDependencies (/opt/vrs/eslnest/node_modules/@nestjs/core/scanner.js:54:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
 1: 0x8dc1c0 node::Abort() [node]
 2: 0x96e1a9  [node]
 3: 0xb5e7cf  [node]
 4: 0xb5f339 v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [node]
 5: 0x2567b1cdbe1d 
Aborted

Please refer to this link <https://github.com/nestjs/nest/issues/1010>

**Comment by bashleigh** [comment]
This issue was because the component's key was still being used on the module instead of provider 👍

**Comment by anhgien** [comment]
Could you fix it asap?
Thanks

**Comment by shekohex** [comment]
Published `v1.1.0` :tada:
